#region race indexes
#macro SHORT_IND 0
#macro MILE_IND 1
#macro MID_IND 2
#macro LONG_IND 3
#macro DIRT_IND 4
#endregion

#region race names
#macro SHORT_STR "Short"
#macro MILE_STR "Mile"
#macro MID_STR "Mid"
#macro LONG_STR "Long"
#macro DIRT_STR "Dirt"
#endregion

#macro HORSES oUmaTeamTracker.ALL_HORSES

#region horses
#macro _ADMIRE_VEGA HORSES[HORSE_INDEX.ADMIRE_VEGA]
#macro _AGNES_TACHYON HORSES[HORSE_INDEX.AGNES_TACHYON]
#macro _AIR_GROOVE HORSES[HORSE_INDEX.AIR_GROOVE]
#macro _BIWA_HAYAHIDE HORSES[HORSE_INDEX.BIWA_HAYAHIDE]
#macro _CURREN_CHAN HORSES[HORSE_INDEX.CURREN_CHAN]
#macro _DAIWA_SCARLET HORSES[HORSE_INDEX.DAIWA_SCARLET]
#macro _EL_CONDOR_PASA HORSES[HORSE_INDEX.EL_CONDOR_PASA]
#macro _FUJI_KISEKI HORSES[HORSE_INDEX.FUJI_KISEKI]
#macro _GOLD_SHIP HORSES[HORSE_INDEX.GOLD_SHIP]
#macro _GRASS_WONDER HORSES[HORSE_INDEX.GRASS_WONDER]
#macro _HARU_URARA HORSES[HORSE_INDEX.HARU_URARA]
#macro _HISHI_AMAZON HORSES[HORSE_INDEX.HISHI_AMAZON]
#macro _KING_HALO HORSES[HORSE_INDEX.KING_HALO]
#macro _MARUZENSKY HORSES[HORSE_INDEX.MARUZENSKY]
#macro _MATIKANE_FUKUKITARU HORSES[HORSE_INDEX.MATIKANE_FUKUKITARU]
#macro _MAYANO_TOP_GUN HORSES[HORSE_INDEX.MAYANO_TOP_GUN]
#macro _MEJIRO_MCQUEEN HORSES[HORSE_INDEX.MEJIRO_MCQUEEN]
#macro _MEJIRO_RYAN HORSES[HORSE_INDEX.MEJIRO_RYAN]
#macro _MIHONO_BOURBON HORSES[HORSE_INDEX.MIHONO_BOURBON]
#macro _NARITA_BRIAN HORSES[HORSE_INDEX.NARITA_BRIAN]
#macro _NICE_NATURE HORSES[HORSE_INDEX.NICE_NATURE]
#macro _OGURI_CAP HORSES[HORSE_INDEX.OGURI_CAP]
#macro _RICE_SHOWER HORSES[HORSE_INDEX.RICE_SHOWER]
#macro _SAKURA_BAKUSHIN_O HORSES[HORSE_INDEX.SAKURA_BAKUSHIN_O]
#macro _SEIUN_SKY HORSES[HORSE_INDEX.SEIUN_SKY]
#macro _SILENCE_SUZUKA HORSES[HORSE_INDEX.SILENCE_SUZUKA]
#macro _SPECIAL_WEEK HORSES[HORSE_INDEX.SPECIAL_WEEK]
#macro _SUPER_CREEK HORSES[HORSE_INDEX.SUPER_CREEK]
#macro _SYMBOLI_RUDOLF HORSES[HORSE_INDEX.SYMBOLI_RUDOLF]
#macro _TAIKI_SHUTTLE HORSES[HORSE_INDEX.TAIKI_SHUTTLE]
#macro _TM_OPERA_O HORSES[HORSE_INDEX.TM_OPERA_O]
#macro _TOKAI_TEIO HORSES[HORSE_INDEX.TOKAI_TEIO]
#macro _VODKA HORSES[HORSE_INDEX.VODKA]
#macro _WINNING_TICKET HORSES[HORSE_INDEX.WINNING_TICKET]
#endregion

#macro RESULTS oStatsController.resultsSearch